apiVersion: v1
kind: Pod
metadata:
  name: secret-using-volume
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: secretvolume
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: secretvolume
    secret:
      secretName: myapi-url-token
