apiVersion: v1
kind: Pod
metadata:
  name: secret-using-env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: SECRET_URL
        valueFrom:
          secretKeyRef:
            name: myapi-url-token
            key: secreturl.txt
      - name: SECRET_TOKEN
        valueFrom:
          secretKeyRef:
            name: myapi-url-token
            key: secrettoken.txt
  restartPolicy: Never
